### ISSUE TITLE
Practica de realidad aumentada con objetos 3d en heroku_Edwin, Alexis, Iván, Taoli

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo_cafe-huerto-el-mamey#2]
[Practica de realidad aumentada con objetos 3d en heroku_Edwin, Alexis, Iván, Taoli.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo_cafe-huerto-el-mamey/files/8310346/Practica.de.realidad.aumentada.con.objetos.3d.en.heroku_Edwin.Alexis.Ivan.Taoli.pdf)

**Comment by Jaci14** [comment]
Contiene todos los elementos pedidos en la practica (portada, introducción, descripción, objetivo, desarrollo, resultado, conclusión y bibliografías) y la aplicación es funcional.

Puntos: 100
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
